language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - 1.12.2
    - 1.10.2

cache:
  directories:
  - $HOME/.gradle
  
sudo: required

before_install:
 - chmod +x gradlew